'mixed-port': !!int '7890'
'allow-lan': !!bool 'true'
'mode': 'rule'
'log-level': 'info'
'external-controller': '127.0.0.1:9090'
'dns':
  'enable': !!bool 'true'
  'enhanced-mode': 'fake-ip'
  'fake-ip-range': '198.18.0.1/16'
  'nameserver':
  - '8.8.8.8'
  - '1.1.1.1'
'proxies':
- 'name': '🇷🇺 Beget — #1'
  'type': 'vless'
  'server': '45.12.75.242'
  'port': !!int '26424'
  'uuid': '633f424e-2b11-48da-a6b3-a849dd71456f'
  'network': 'raw'
  'udp': !!bool 'true'
  'tls': !!bool 'true'
  'servername': 'ya.ru'
  'reality-opts':
    'public-key': 'l8AubqcxQO-HRFJy4pZL1vbLOo-eXit69s-XulSELE0'
    'short-id': '23103e1e'
  'client-fingerprint': 'chrome'
- 'name': '🇷🇺 Beget — #2'
  'type': 'vless'
  'server': '45.12.75.242'
  'port': !!int '26424'
  'uuid': '633f424e-2b11-48da-a6b3-a849dd71456f'
  'network': 'raw'
  'udp': !!bool 'true'
  'tls': !!bool 'true'
  'servername': 'ya.ru'
  'reality-opts':
    'public-key': 'l8AubqcxQO-HRFJy4pZL1vbLOo-eXit69s-XulSELE0'
    'short-id': '23103e1e'
  'client-fingerprint': 'qq'
- 'name': '🇷🇺 Beget — #3'
  'type': 'vless'
  'server': '45.12.75.242'
  'port': !!int '26424'
  'uuid': '633f424e-2b11-48da-a6b3-a849dd71456f'
  'network': 'raw'
  'udp': !!bool 'true'
  'tls': !!bool 'true'
  'servername': 'ya.ru'
  'reality-opts':
    'public-key': 'l8AubqcxQO-HRFJy4pZL1vbLOo-eXit69s-XulSELE0'
    'short-id': '23103e1e'
  'client-fingerprint': 'chrome'
- 'name': '🇷🇺 Beget — #4'
  'type': 'vless'
  'server': '45.12.75.242'
  'port': !!int '26424'
  'uuid': '633f424e-2b11-48da-a6b3-a849dd71456f'
  'network': 'raw'
  'udp': !!bool 'true'
  'tls': !!bool 'true'
  'servername': 'ya.ru'
  'reality-opts':
    'public-key': 'l8AubqcxQO-HRFJy4pZL1vbLOo-eXit69s-XulSELE0'
    'short-id': '23103e1e'
  'client-fingerprint': 'firefox'
- 'name': '🇨🇿 Czechia — #5'
  'type': 'vless'
  'server': '78.159.247.170'
  'port': !!int '443'
  'uuid': '92089155-6602-4122-86d4-fe6de20e8c4d'
  'network': 'raw'
  'udp': !!bool 'true'
  'tls': !!bool 'true'
  'servername': 'kinopoisk.ru'
  'reality-opts':
    'public-key': 'NsTRRl4ofT64w0VwmkpOWE8yfiXLcEqgwgi-9SGnXTA'
    'short-id': 'a1b2c3d4'
  'flow': 'xtls-rprx-vision'
  'client-fingerprint': 'firefox'
- 'name': '🇨🇿 Czechia — #6'
  'type': 'vless'
  'server': '78.159.247.205'
  'port': !!int '443'
  'uuid': '92089155-6602-4122-86d4-fe6de20e8c4d'
  'network': 'raw'
  'udp': !!bool 'true'
  'tls': !!bool 'true'
  'servername': 'kinopoisk.ru'
  'reality-opts':
    'public-key': 'NsTRRl4ofT64w0VwmkpOWE8yfiXLcEqgwgi-9SGnXTA'
    'short-id': 'a1b2c3d4'
  'flow': 'xtls-rprx-vision'
  'client-fingerprint': 'firefox'
- 'name': '🇨🇿 Czechia — #7'
  'type': 'vless'
  'server': '78.159.247.214'
  'port': !!int '443'
  'uuid': '92089155-6602-4122-86d4-fe6de20e8c4d'
  'network': 'raw'
  'udp': !!bool 'true'
  'tls': !!bool 'true'
  'servername': 'kinopoisk.ru'
  'reality-opts':
    'public-key': 'NsTRRl4ofT64w0VwmkpOWE8yfiXLcEqgwgi-9SGnXTA'
    'short-id': 'a1b2c3d4'
  'flow': 'xtls-rprx-vision'
  'client-fingerprint': 'firefox'
- 'name': '🇩🇪 Germany — #8'
  'type': 'vless'
  'server': '188.225.33.112'
  'port': !!int '443'
  'uuid': '85b72048-d250-43e7-a830-206b28c9f5c3'
  'network': 'grpc'
  'udp': !!bool 'true'
  'tls': !!bool 'true'
  'servername': 'smartcaptcha.yandexcloud.net'
  'reality-opts':
    'public-key': 'miH_ROFipWmvm-PqF1dSgN1jp7nIQZyKFhdILXXrsQI'
    'short-id': '91c91e25817ab51c'
  'client-fingerprint': 'firefox'
- 'name': '🇩🇪 Germany — #9'
  'type': 'vless'
  'server': '188.72.103.4'
  'port': !!int '443'
  'uuid': '1f959100-a98b-47fb-84fa-359246dc458a'
  'network': 'ws'
  'udp': !!bool 'true'
- 'name': '🇩🇪 Germany — #10'
  'type': 'vless'
  'server': '188.72.103.4'
  'port': !!int '443'
  'uuid': '1f959100-a98b-47fb-84fa-359246dc458a'
  'network': 'ws'
  'udp': !!bool 'true'
- 'name': '🇩🇪 Germany — #11'
  'type': 'vless'
  'server': '188.72.103.4'
  'port': !!int '443'
  'uuid': '1f959100-a98b-47fb-84fa-359246dc458a'
  'network': 'ws'
  'udp': !!bool 'true'
- 'name': '🇩🇪 Germany — #12'
  'type': 'vless'
  'server': '185.229.9.175'
  'port': !!int '443'
  'uuid': 'c5694dc5-39fd-4a92-8430-3837baa522a3'
  'network': 'raw'
  'udp': !!bool 'true'
  'tls': !!bool 'true'
  'servername': 'api.ok.ru'
  'reality-opts':
    'public-key': 'Eutx4frdhG1y7THj7k3CjazAsrCMj932RtbV4a1QfQk'
    'short-id': 'd5b6308860d578bb'
  'flow': 'xtls-rprx-vision'
  'client-fingerprint': 'firefox'
- 'name': '🇪🇪 Estonia — #13'
  'type': 'vless'
  'server': '91.215.40.6'
  'port': !!int '443'
  'uuid': 'e3c3b722-1264-4cdc-a97c-b0a1bb73cd67'
  'network': 'grpc'
  'udp': !!bool 'true'
  'tls': !!bool 'true'
  'servername': 'id.dframe.app'
  'reality-opts':
    'public-key': 'ivgTfLR13A6xBsicIA28OPoav2tXlsstTTmGuETfnSk'
    'short-id': '5c766813929a1fdd'
  'client-fingerprint': 'chrome'
- 'name': '🇬🇧 United Kingdom — #15'
  'type': 'vless'
  'server': '188.225.57.173'
  'port': !!int '443'
  'uuid': 'fcbc0571-7b14-4699-830e-11cf3aa0ad6b'
  'network': 'ws'
  'udp': !!bool 'true'
- 'name': '🇬🇧 United Kingdom — #16'
  'type': 'vless'
  'server': '188.225.57.173'
  'port': !!int '443'
  'uuid': 'fcbc0571-7b14-4699-830e-11cf3aa0ad6b'
  'network': 'ws'
  'udp': !!bool 'true'
- 'name': '🇬🇧 United Kingdom — #17'
  'type': 'vless'
  'server': '188.225.57.173'
  'port': !!int '443'
  'uuid': 'fcbc0571-7b14-4699-830e-11cf3aa0ad6b'
  'network': 'ws'
  'udp': !!bool 'true'
- 'name': '🇬🇧 United Kingdom — #18'
  'type': 'vless'
  'server': '188.225.57.173'
  'port': !!int '443'
  'uuid': 'fcbc0571-7b14-4699-830e-11cf3aa0ad6b'
  'network': 'ws'
  'udp': !!bool 'true'
- 'name': '🇬🇧 United Kingdom — #19'
  'type': 'vless'
  'server': '188.225.57.173'
  'port': !!int '443'
  'uuid': 'fcbc0571-7b14-4699-830e-11cf3aa0ad6b'
  'network': 'ws'
  'udp': !!bool 'true'
- 'name': '🇳🇱 The Netherlands — #21'
  'type': 'vless'
  'server': '188.225.45.152'
  'port': !!int '12096'
  'uuid': 'a95b3155-bc03-4789-b367-944b83be8f86'
  'network': 'raw'
  'udp': !!bool 'true'
  'tls': !!bool 'true'
  'servername': 'www.x5.ru'
  'reality-opts':
    'public-key': 'Nq6KRzyjC95-W9JtG13EwPzNccKnZwMzhxEM_3zkdk8'
    'short-id': 'fd5b64ba'
  'flow': 'xtls-rprx-vision'
  'client-fingerprint': 'edge'
'proxy-groups':
- 'name': 'PROXY'
  'type': 'select'
  'proxies':
  - '🚀 Авто'
  - '📺 YouTube'
  - '🎮 League'
  - '🇩🇪 Frankfurt'
  - '🇵🇱 Polska'
  - '🇪🇪 Eesti'
  - '🇭🇺 Hungary'
  - '⚡ Российские'
  - '🇷🇺 Beget — #1'
  - '🇷🇺 Beget — #2'
  - '🇷🇺 Beget — #3'
  - '🇷🇺 Beget — #4'
  - '🇨🇿 Czechia — #5'
  - '🇨🇿 Czechia — #6'
  - '🇨🇿 Czechia — #7'
  - '🇩🇪 Germany — #8'
  - '🇩🇪 Germany — #9'
  - '🇩🇪 Germany — #10'
  - '🇩🇪 Germany — #11'
  - '🇩🇪 Germany — #12'
  - '🇪🇪 Estonia — #13'
  - '🇬🇧 United Kingdom — #15'
  - '🇬🇧 United Kingdom — #16'
  - '🇬🇧 United Kingdom — #17'
  - '🇬🇧 United Kingdom — #18'
  - '🇬🇧 United Kingdom — #19'
  - '🇳🇱 The Netherlands — #21'
- 'name': '🚀 Авто'
  'type': 'url-test'
  'proxies':
  - '🇷🇺 Beget — #1'
  - '🇷🇺 Beget — #2'
  - '🇷🇺 Beget — #3'
  - '🇷🇺 Beget — #4'
  - '🇨🇿 Czechia — #5'
  - '🇨🇿 Czechia — #6'
  - '🇨🇿 Czechia — #7'
  - '🇩🇪 Germany — #8'
  - '🇩🇪 Germany — #9'
  - '🇩🇪 Germany — #10'
  - '🇩🇪 Germany — #11'
  - '🇩🇪 Germany — #12'
  - '🇪🇪 Estonia — #13'
  - '🇬🇧 United Kingdom — #15'
  - '🇬🇧 United Kingdom — #16'
  - '🇬🇧 United Kingdom — #17'
  - '🇬🇧 United Kingdom — #18'
  - '🇬🇧 United Kingdom — #19'
  - '🇳🇱 The Netherlands — #21'
  'url': 'https://www.google.com/generate_204'
  'interval': !!int '60'
  'tolerance': !!int '100'
- 'name': '📺 YouTube'
  'type': 'url-test'
  'proxies':
  - '🇨🇿 Czechia — #5'
  - '🇨🇿 Czechia — #6'
  - '🇨🇿 Czechia — #7'
  - '🇩🇪 Germany — #8'
  - '🇩🇪 Germany — #9'
  - '🇩🇪 Germany — #10'
  - '🇩🇪 Germany — #11'
  - '🇩🇪 Germany — #12'
  - '🇪🇪 Estonia — #13'
  - '🇬🇧 United Kingdom — #15'
  - '🇬🇧 United Kingdom — #16'
  - '🇬🇧 United Kingdom — #17'
  - '🇬🇧 United Kingdom — #18'
  - '🇬🇧 United Kingdom — #19'
  - '🇳🇱 The Netherlands — #21'
  'url': 'https://www.youtube.com/generate_204'
  'interval': !!int '120'
  'tolerance': !!int '150'
- 'name': '🎮 League'
  'type': 'url-test'
  'proxies': &id001
  - '🇷🇺 Beget — #1'
  - '🇷🇺 Beget — #2'
  - '🇷🇺 Beget — #3'
  - '🇷🇺 Beget — #4'
  'url': 'https://www.google.com/generate_204'
  'interval': !!int '60'
  'tolerance': !!int '30'
- 'name': '🇩🇪 Frankfurt'
  'type': 'url-test'
  'proxies':
  - '🇩🇪 Germany — #8'
  - '🇩🇪 Germany — #9'
  - '🇩🇪 Germany — #10'
  - '🇩🇪 Germany — #11'
  - '🇩🇪 Germany — #12'
  'url': 'https://cloudflare.com/cdn-cgi/trace'
  'interval': !!int '60'
  'tolerance': !!int '50'
- 'name': '🇵🇱 Polska'
  'type': 'url-test'
  'proxies':
  - '🇨🇿 Czechia — #5'
  - '🇨🇿 Czechia — #6'
  - '🇨🇿 Czechia — #7'
  - '🇩🇪 Germany — #8'
  - '🇩🇪 Germany — #9'
  - '🇩🇪 Germany — #10'
  - '🇩🇪 Germany — #11'
  - '🇩🇪 Germany — #12'
  - '🇪🇪 Estonia — #13'
  - '🇬🇧 United Kingdom — #15'
  - '🇬🇧 United Kingdom — #16'
  - '🇬🇧 United Kingdom — #17'
  - '🇬🇧 United Kingdom — #18'
  - '🇬🇧 United Kingdom — #19'
  - '🇳🇱 The Netherlands — #21'
  'url': 'https://cloudflare.com/cdn-cgi/trace'
  'interval': !!int '60'
  'tolerance': !!int '50'
- 'name': '🇪🇪 Eesti'
  'type': 'url-test'
  'proxies':
  - '🇪🇪 Estonia — #13'
  'url': 'https://cloudflare.com/cdn-cgi/trace'
  'interval': !!int '60'
  'tolerance': !!int '50'
- 'name': '🇭🇺 Hungary'
  'type': 'url-test'
  'proxies':
  - '🇨🇿 Czechia — #5'
  - '🇨🇿 Czechia — #6'
  - '🇨🇿 Czechia — #7'
  - '🇩🇪 Germany — #8'
  - '🇩🇪 Germany — #9'
  - '🇩🇪 Germany — #10'
  - '🇩🇪 Germany — #11'
  - '🇩🇪 Germany — #12'
  - '🇪🇪 Estonia — #13'
  - '🇬🇧 United Kingdom — #15'
  - '🇬🇧 United Kingdom — #16'
  - '🇬🇧 United Kingdom — #17'
  - '🇬🇧 United Kingdom — #18'
  - '🇬🇧 United Kingdom — #19'
  - '🇳🇱 The Netherlands — #21'
  'url': 'https://cloudflare.com/cdn-cgi/trace'
  'interval': !!int '60'
  'tolerance': !!int '50'
- 'name': '⚡ Российские'
  'type': 'url-test'
  'proxies': *id001
  'url': 'https://yandex.ru/internet'
  'interval': !!int '60'
  'tolerance': !!int '30'
'rules':
- 'DOMAIN-SUFFIX,youtube.com,📺 YouTube'
- 'DOMAIN-SUFFIX,googlevideo.com,📺 YouTube'
- 'DOMAIN-SUFFIX,ytimg.com,📺 YouTube'
- 'DOMAIN-SUFFIX,ggpht.com,📺 YouTube'
- 'DOMAIN-SUFFIX,youtu.be,📺 YouTube'
- 'DOMAIN,youtube.googleapis.com,📺 YouTube'
- 'DOMAIN-SUFFIX,twitch.tv,📺 YouTube'
- 'DOMAIN-SUFFIX,netflix.com,📺 YouTube'
- 'DOMAIN-SUFFIX,hulu.com,📺 YouTube'
- 'MATCH,PROXY'
