'mixed-port': !!int '7890'
'allow-lan': !!bool 'true'
'mode': 'rule'
'log-level': 'info'
'external-controller': '127.0.0.1:9090'
'dns':
  'enable': !!bool 'true'
  'enhanced-mode': 'fake-ip'
  'fake-ip-range': '198.18.0.1/16'
  'nameserver':
  - '8.8.8.8'
  - '1.1.1.1'
'proxies':
- 'name': '🇷🇺 VK — #1'
  'type': 'vless'
  'server': '95.163.214.43'
  'port': !!int '443'
  'uuid': '88ce17fc-7c6c-43a7-98a4-33fb59697b17'
  'network': 'xhttp'
  'udp': !!bool 'true'
  'tls': !!bool 'true'
  'servername': 'ok.ru'
  'reality-opts':
    'public-key': 'VdG4ntV15FfNWV4rvSny2mvOTSXfOUVKHNC0dOyXY2s'
    'short-id': '864fbb122f15b43d'
  'client-fingerprint': 'ios'
- 'name': '🇷🇺 Beget — #2'
  'type': 'vless'
  'server': '45.12.75.242'
  'port': !!int '26424'
  'uuid': '633f424e-2b11-48da-a6b3-a849dd71456f'
  'network': 'raw'
  'udp': !!bool 'true'
  'tls': !!bool 'true'
  'servername': 'ya.ru'
  'reality-opts':
    'public-key': 'l8AubqcxQO-HRFJy4pZL1vbLOo-eXit69s-XulSELE0'
    'short-id': '23103e1e'
  'client-fingerprint': 'chrome'
- 'name': '🇷🇺 Beget — #3'
  'type': 'vless'
  'server': '45.12.75.242'
  'port': !!int '26424'
  'uuid': '633f424e-2b11-48da-a6b3-a849dd71456f'
  'network': 'raw'
  'udp': !!bool 'true'
  'tls': !!bool 'true'
  'servername': 'ya.ru'
  'reality-opts':
    'public-key': 'l8AubqcxQO-HRFJy4pZL1vbLOo-eXit69s-XulSELE0'
    'short-id': '23103e1e'
  'client-fingerprint': 'qq'
- 'name': '🇷🇺 Beget — #4'
  'type': 'vless'
  'server': '45.12.75.242'
  'port': !!int '26424'
  'uuid': '633f424e-2b11-48da-a6b3-a849dd71456f'
  'network': 'raw'
  'udp': !!bool 'true'
  'tls': !!bool 'true'
  'servername': 'ya.ru'
  'reality-opts':
    'public-key': 'l8AubqcxQO-HRFJy4pZL1vbLOo-eXit69s-XulSELE0'
    'short-id': '23103e1e'
  'client-fingerprint': 'chrome'
- 'name': '🇷🇺 Beget — #5'
  'type': 'vless'
  'server': '45.12.75.242'
  'port': !!int '26424'
  'uuid': '633f424e-2b11-48da-a6b3-a849dd71456f'
  'network': 'raw'
  'udp': !!bool 'true'
  'tls': !!bool 'true'
  'servername': 'ya.ru'
  'reality-opts':
    'public-key': 'l8AubqcxQO-HRFJy4pZL1vbLOo-eXit69s-XulSELE0'
    'short-id': '23103e1e'
  'client-fingerprint': 'firefox'
- 'name': '🇷🇺 MegaMax Network — #6'
  'type': 'vless'
  'server': '212.67.9.113'
  'port': !!int '2200'
  'uuid': '2aa7f4b1-e859-46d0-b8ac-8587811ab7b1'
  'network': 'ws'
  'udp': !!bool 'true'
- 'name': '🇷🇺 ProCloud — #7'
  'type': 'vless'
  'server': '185.147.27.183'
  'port': !!int '8443'
  'uuid': '379998c5-2a71-4202-9c74-522e0c3c5404'
  'network': 'raw'
  'udp': !!bool 'true'
- 'name': '🇷🇺 UFO Hosting — #8'
  'type': 'vless'
  'server': '217.16.31.162'
  'port': !!int '443'
  'uuid': 'af9c2bcf-fe68-4379-9c78-6e5f1b4af0e2'
  'network': 'raw'
  'udp': !!bool 'true'
  'tls': !!bool 'true'
  'servername': 'max.ru'
  'reality-opts':
    'public-key': 'SHIYN7zN9aFVxwKK-bIvDbhUgtHvlBhDi1qSl2sWwRw'
    'short-id': 'e7'
  'flow': 'xtls-rprx-vision'
  'client-fingerprint': 'safari'
- 'name': '🇷🇺 UFO Hosting — #9'
  'type': 'vless'
  'server': '217.16.31.162'
  'port': !!int '443'
  'uuid': 'af9c2bcf-fe68-4379-9c78-6e5f1b4af0e2'
  'network': 'raw'
  'udp': !!bool 'true'
  'tls': !!bool 'true'
  'servername': 'max.ru'
  'reality-opts':
    'public-key': 'SHIYN7zN9aFVxwKK-bIvDbhUgtHvlBhDi1qSl2sWwRw'
    'short-id': 'e7'
  'flow': 'xtls-rprx-vision'
  'client-fingerprint': 'ios'
- 'name': '🇷🇺 UFO Hosting — #10'
  'type': 'vless'
  'server': '217.16.31.162'
  'port': !!int '443'
  'uuid': 'af9c2bcf-fe68-4379-9c78-6e5f1b4af0e2'
  'network': 'raw'
  'udp': !!bool 'true'
  'tls': !!bool 'true'
  'servername': 'max.ru'
  'reality-opts':
    'public-key': 'SHIYN7zN9aFVxwKK-bIvDbhUgtHvlBhDi1qSl2sWwRw'
    'short-id': 'e7'
  'flow': 'xtls-rprx-vision'
  'client-fingerprint': 'edge'
- 'name': '🇷🇺 UFO Hosting — #11'
  'type': 'vless'
  'server': '217.16.31.162'
  'port': !!int '443'
  'uuid': 'af9c2bcf-fe68-4379-9c78-6e5f1b4af0e2'
  'network': 'raw'
  'udp': !!bool 'true'
  'tls': !!bool 'true'
  'servername': 'max.ru'
  'reality-opts':
    'public-key': 'SHIYN7zN9aFVxwKK-bIvDbhUgtHvlBhDi1qSl2sWwRw'
    'short-id': 'e7'
  'flow': 'xtls-rprx-vision'
  'client-fingerprint': 'firefox'
- 'name': '🇷🇺 UFO Hosting — #12'
  'type': 'vless'
  'server': '217.16.31.162'
  'port': !!int '443'
  'uuid': 'af9c2bcf-fe68-4379-9c78-6e5f1b4af0e2'
  'network': 'raw'
  'udp': !!bool 'true'
  'tls': !!bool 'true'
  'servername': 'max.ru'
  'reality-opts':
    'public-key': 'SHIYN7zN9aFVxwKK-bIvDbhUgtHvlBhDi1qSl2sWwRw'
    'short-id': 'e7'
  'flow': 'xtls-rprx-vision'
  'client-fingerprint': 'chrome'
- 'name': '🇷🇺 UFO Hosting — #13'
  'type': 'vless'
  'server': '217.16.31.162'
  'port': !!int '443'
  'uuid': 'af9c2bcf-fe68-4379-9c78-6e5f1b4af0e2'
  'network': 'raw'
  'udp': !!bool 'true'
  'tls': !!bool 'true'
  'servername': 'max.ru'
  'reality-opts':
    'public-key': 'SHIYN7zN9aFVxwKK-bIvDbhUgtHvlBhDi1qSl2sWwRw'
    'short-id': 'e7'
  'flow': 'xtls-rprx-vision'
  'client-fingerprint': 'qq'
- 'name': '🇷🇺 UFO Hosting — #14'
  'type': 'vless'
  'server': '217.16.31.218'
  'port': !!int '443'
  'uuid': 'af9c2bcf-fe68-4379-9c78-6e5f1b4af0e2'
  'network': 'raw'
  'udp': !!bool 'true'
  'tls': !!bool 'true'
  'servername': 'max.ru'
  'reality-opts':
    'public-key': 'SHIYN7zN9aFVxwKK-bIvDbhUgtHvlBhDi1qSl2sWwRw'
    'short-id': 'e7'
  'flow': 'xtls-rprx-vision'
  'client-fingerprint': 'chrome'
- 'name': '🇷🇺 UFO Hosting — #15'
  'type': 'vless'
  'server': '217.16.31.218'
  'port': !!int '443'
  'uuid': 'af9c2bcf-fe68-4379-9c78-6e5f1b4af0e2'
  'network': 'raw'
  'udp': !!bool 'true'
  'tls': !!bool 'true'
  'servername': 'max.ru'
  'reality-opts':
    'public-key': 'SHIYN7zN9aFVxwKK-bIvDbhUgtHvlBhDi1qSl2sWwRw'
    'short-id': 'e7'
  'flow': 'xtls-rprx-vision'
  'client-fingerprint': 'firefox'
- 'name': '🇨🇿 Czechia — #16'
  'type': 'vless'
  'server': '78.159.247.205'
  'port': !!int '443'
  'uuid': '92089155-6602-4122-86d4-fe6de20e8c4d'
  'network': 'raw'
  'udp': !!bool 'true'
  'tls': !!bool 'true'
  'servername': 'kinopoisk.ru'
  'reality-opts':
    'public-key': 'NsTRRl4ofT64w0VwmkpOWE8yfiXLcEqgwgi-9SGnXTA'
    'short-id': 'a1b2c3d4'
  'flow': 'xtls-rprx-vision'
  'client-fingerprint': 'firefox'
- 'name': '🇨🇿 Czechia — #17'
  'type': 'vless'
  'server': '78.159.247.170'
  'port': !!int '443'
  'uuid': '92089155-6602-4122-86d4-fe6de20e8c4d'
  'network': 'raw'
  'udp': !!bool 'true'
  'tls': !!bool 'true'
  'servername': 'kinopoisk.ru'
  'reality-opts':
    'public-key': 'NsTRRl4ofT64w0VwmkpOWE8yfiXLcEqgwgi-9SGnXTA'
    'short-id': 'a1b2c3d4'
  'flow': 'xtls-rprx-vision'
  'client-fingerprint': 'firefox'
- 'name': '🇩🇪 Germany — #24'
  'type': 'vless'
  'server': '91.218.230.240'
  'port': !!int '20443'
  'uuid': 'd4719d52-c3fc-4651-98e1-535dbd77dbcf'
  'network': 'raw'
  'udp': !!bool 'true'
- 'name': '🇳🇱 The Netherlands — #25'
  'type': 'vless'
  'server': '95.129.236.124'
  'port': !!int '443'
  'uuid': 'ecf728d9-1555-4e12-b178-1d8bd98465e4'
  'network': 'ws'
  'udp': !!bool 'true'
- 'name': '🇳🇱 The Netherlands — #26'
  'type': 'vless'
  'server': '95.129.236.124'
  'port': !!int '443'
  'uuid': 'ecf728d9-1555-4e12-b178-1d8bd98465e4'
  'network': 'ws'
  'udp': !!bool 'true'
- 'name': '🇳🇱 The Netherlands — #29'
  'type': 'vless'
  'server': '201.24.117.25'
  'port': !!int '19210'
  'uuid': '4e358a16-f113-4779-8691-d88acd1d2395'
  'network': 'raw'
  'udp': !!bool 'true'
  'tls': !!bool 'true'
  'servername': 'travel.yandex.com'
  'reality-opts':
    'public-key': 'rvcGpldftiQ1_SD8XFNLq2L9VkU0yME0YYgTw6guHhE'
    'short-id': '5b'
  'flow': 'xtls-rprx-vision'
  'client-fingerprint': 'firefox'
- 'name': '🇳🇱 The Netherlands — #30'
  'type': 'vless'
  'server': '188.72.103.4'
  'port': !!int '443'
  'uuid': '211ac011-cebe-4521-968e-401259b3cdea'
  'network': 'xhttp'
  'udp': !!bool 'true'
- 'name': '🇵🇱 Poland — #31'
  'type': 'vless'
  'server': '188.72.103.4'
  'port': !!int '443'
  'uuid': 'ce2f9c73-3618-41ce-899b-fd49cc013011'
  'network': 'xhttp'
  'udp': !!bool 'true'
'proxy-groups':
- 'name': 'PROXY'
  'type': 'select'
  'proxies':
  - '🚀 Авто'
  - '📺 YouTube'
  - '🎮 League'
  - '🇩🇪 Frankfurt'
  - '🇵🇱 Polska'
  - '🇪🇪 Eesti'
  - '🇭🇺 Hungary'
  - '⚡ Российские'
  - '🇷🇺 VK — #1'
  - '🇷🇺 Beget — #2'
  - '🇷🇺 Beget — #3'
  - '🇷🇺 Beget — #4'
  - '🇷🇺 Beget — #5'
  - '🇷🇺 MegaMax Network — #6'
  - '🇷🇺 ProCloud — #7'
  - '🇷🇺 UFO Hosting — #8'
  - '🇷🇺 UFO Hosting — #9'
  - '🇷🇺 UFO Hosting — #10'
  - '🇷🇺 UFO Hosting — #11'
  - '🇷🇺 UFO Hosting — #12'
  - '🇷🇺 UFO Hosting — #13'
  - '🇷🇺 UFO Hosting — #14'
  - '🇷🇺 UFO Hosting — #15'
  - '🇨🇿 Czechia — #16'
  - '🇨🇿 Czechia — #17'
  - '🇩🇪 Germany — #24'
  - '🇳🇱 The Netherlands — #25'
  - '🇳🇱 The Netherlands — #26'
  - '🇳🇱 The Netherlands — #29'
  - '🇳🇱 The Netherlands — #30'
  - '🇵🇱 Poland — #31'
- 'name': '🚀 Авто'
  'type': 'url-test'
  'proxies':
  - '🇷🇺 VK — #1'
  - '🇷🇺 Beget — #2'
  - '🇷🇺 Beget — #3'
  - '🇷🇺 Beget — #4'
  - '🇷🇺 Beget — #5'
  - '🇷🇺 MegaMax Network — #6'
  - '🇷🇺 ProCloud — #7'
  - '🇷🇺 UFO Hosting — #8'
  - '🇷🇺 UFO Hosting — #9'
  - '🇷🇺 UFO Hosting — #10'
  - '🇷🇺 UFO Hosting — #11'
  - '🇷🇺 UFO Hosting — #12'
  - '🇷🇺 UFO Hosting — #13'
  - '🇷🇺 UFO Hosting — #14'
  - '🇷🇺 UFO Hosting — #15'
  - '🇨🇿 Czechia — #16'
  - '🇨🇿 Czechia — #17'
  - '🇩🇪 Germany — #24'
  - '🇳🇱 The Netherlands — #25'
  - '🇳🇱 The Netherlands — #26'
  - '🇳🇱 The Netherlands — #29'
  - '🇳🇱 The Netherlands — #30'
  - '🇵🇱 Poland — #31'
  'url': 'https://www.google.com/generate_204'
  'interval': !!int '60'
  'tolerance': !!int '100'
- 'name': '📺 YouTube'
  'type': 'url-test'
  'proxies':
  - '🇨🇿 Czechia — #16'
  - '🇨🇿 Czechia — #17'
  - '🇩🇪 Germany — #24'
  - '🇳🇱 The Netherlands — #25'
  - '🇳🇱 The Netherlands — #26'
  - '🇳🇱 The Netherlands — #29'
  - '🇳🇱 The Netherlands — #30'
  - '🇵🇱 Poland — #31'
  'url': 'https://www.youtube.com/generate_204'
  'interval': !!int '120'
  'tolerance': !!int '150'
- 'name': '🎮 League'
  'type': 'url-test'
  'proxies': &id001
  - '🇷🇺 VK — #1'
  - '🇷🇺 Beget — #2'
  - '🇷🇺 Beget — #3'
  - '🇷🇺 Beget — #4'
  - '🇷🇺 Beget — #5'
  - '🇷🇺 MegaMax Network — #6'
  - '🇷🇺 ProCloud — #7'
  - '🇷🇺 UFO Hosting — #8'
  - '🇷🇺 UFO Hosting — #9'
  - '🇷🇺 UFO Hosting — #10'
  - '🇷🇺 UFO Hosting — #11'
  - '🇷🇺 UFO Hosting — #12'
  - '🇷🇺 UFO Hosting — #13'
  - '🇷🇺 UFO Hosting — #14'
  - '🇷🇺 UFO Hosting — #15'
  'url': 'https://www.google.com/generate_204'
  'interval': !!int '60'
  'tolerance': !!int '30'
- 'name': '🇩🇪 Frankfurt'
  'type': 'url-test'
  'proxies':
  - '🇩🇪 Germany — #24'
  'url': 'https://cloudflare.com/cdn-cgi/trace'
  'interval': !!int '60'
  'tolerance': !!int '50'
- 'name': '🇵🇱 Polska'
  'type': 'url-test'
  'proxies':
  - '🇵🇱 Poland — #31'
  'url': 'https://cloudflare.com/cdn-cgi/trace'
  'interval': !!int '60'
  'tolerance': !!int '50'
- 'name': '🇪🇪 Eesti'
  'type': 'url-test'
  'proxies':
  - '🇨🇿 Czechia — #16'
  - '🇨🇿 Czechia — #17'
  - '🇩🇪 Germany — #24'
  - '🇳🇱 The Netherlands — #25'
  - '🇳🇱 The Netherlands — #26'
  - '🇳🇱 The Netherlands — #29'
  - '🇳🇱 The Netherlands — #30'
  - '🇵🇱 Poland — #31'
  'url': 'https://cloudflare.com/cdn-cgi/trace'
  'interval': !!int '60'
  'tolerance': !!int '50'
- 'name': '🇭🇺 Hungary'
  'type': 'url-test'
  'proxies':
  - '🇨🇿 Czechia — #16'
  - '🇨🇿 Czechia — #17'
  - '🇩🇪 Germany — #24'
  - '🇳🇱 The Netherlands — #25'
  - '🇳🇱 The Netherlands — #26'
  - '🇳🇱 The Netherlands — #29'
  - '🇳🇱 The Netherlands — #30'
  - '🇵🇱 Poland — #31'
  'url': 'https://cloudflare.com/cdn-cgi/trace'
  'interval': !!int '60'
  'tolerance': !!int '50'
- 'name': '⚡ Российские'
  'type': 'url-test'
  'proxies': *id001
  'url': 'https://yandex.ru/internet'
  'interval': !!int '60'
  'tolerance': !!int '30'
'rules':
- 'DOMAIN-SUFFIX,youtube.com,📺 YouTube'
- 'DOMAIN-SUFFIX,googlevideo.com,📺 YouTube'
- 'DOMAIN-SUFFIX,ytimg.com,📺 YouTube'
- 'DOMAIN-SUFFIX,ggpht.com,📺 YouTube'
- 'DOMAIN-SUFFIX,youtu.be,📺 YouTube'
- 'DOMAIN,youtube.googleapis.com,📺 YouTube'
- 'DOMAIN-SUFFIX,twitch.tv,📺 YouTube'
- 'DOMAIN-SUFFIX,netflix.com,📺 YouTube'
- 'DOMAIN-SUFFIX,hulu.com,📺 YouTube'
- 'MATCH,PROXY'
