name: Convert VLESS to Clash YAML

on:
  schedule:
    # Запускать каждый час
    - cron: '0 * * * *'
  workflow_dispatch:  # Можно запустить вручную
  push:
    branches:
      - main

jobs:
  convert:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          pip install pyyaml requests
          
      - name: Download VLESS configs
        run: |
          curl -o vless_lite.txt https://raw.githubusercontent.com/zieng2/wl/main/vless_lite.txt
          
      - name: Convert to Clash YAML
        run: |
          python convert.py
          
      - name: Commit and push if changed
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          git add -A
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-update Clash configs $(date '+%Y-%m-%d %H:%M:%S')" && git push)
